# :::::::::::::::::::::::::::::::::::::::::::::::
# Server Port, HTTPS(SSL) Zertifikat
# :::::::::::::::::::::::::::::::::::::::::::::::
spring.application.name=HiobsServer
server.address=0.0.0.0

# hiobsServer Zertifikat HTTPS(SSL) (Port 8080)
server.port=8080
server.ssl.key-store=classpath:hiobs-keystore.p12
server.ssl.key-store-password=hiobs123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=hiobs

# ==========================================================
# Thymeleaf, suffix / prefix /, ab ver 3.4.8(spring boot) nicht notwendig
#===========================================================
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

# ==========================================================
# = Mailer Properties
#===========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unbekanten@gmail.com
spring.mail.password=fmpkayerosbtqubk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#==========================================================
# H2 + JAR
# Jar erstellen in intelliJ terminal ohne Test für Strato Server(gibt kein Fehler aus)
# paulrichter@localhost HiobsServer % ./mvnw clean package -DskipTests
# Terminal: java -jar /Users/paulrichter/.m2/repository/com/h2database/h2/2.4.240/h2-2.4.240.jar
#==========================================================
# admin database H2 (in project integriert, für jar-datei nicht ändern)
spring.datasource.admin.jdbcUrl=jdbc:h2:file:./h2database/adminHiobs
spring.datasource.admin.driverClassName=org.h2.Driver
spring.datasource.admin.username=sa
spring.datasource.admin.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# hibernate, für die Tabellen erstellung
spring.jpa.hibernate.ddl-auto=update
#WARNUNG in console: die 'spring.jpa.open-in-view' is enabled by default.
spring.jpa.open-in-view = false

#==========================================================
# MongoDB Verbindung localhost:27017 (Lokal für die Entwicklung)
# ACHTUNG: für automatische erstellung von Datenbank, configuration/MongoConfig
#==========================================================
spring.data.mongodb.uri=mongodb://localhost:27017/hiobspost

# Falls Sie später auf dem Server eine Authentifizierung einrichten:
# spring.data.mongodb.username=hiobs
# spring.data.mongodb.password=hiobsPost


# :::::::::::::::::::::::::::::::::::::::::::::::
#   Pom.xml: Daten aus dem pom.xml abrufen und
#   Controller: @Value("${project.version}")
#               private String versions;
# :::::::::::::::::::::::::::::::::::::::::::::::
project.groupId=@pom.groupId@
project.artifactId=@pom.artifactId@
project.name=@pom.name@
project.version=@pom.version@
