# :::::::::::::::::::::::::::::::::::::::::::::::
# Server Port, HTTPS(SSL) Zertifikat
# :::::::::::::::::::::::::::::::::::::::::::::::
spring.application.name=HiobsServer
#server.address=0.0.0.0
server.port=8080

# hiobsServer Zertifikat HTTPS(SSL) (Port 8080)
server.ssl.key-store=classpath:hiobs-keystore.p12
server.ssl.key-store-password=hiobs123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=hiobs

# ==========================================================
# Thymeleaf, suffix / prefix /, ab ver 3.4.8(spring boot) nicht notwendig
#===========================================================
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

# ==========================================================
# = Mailer Properties, von Google & Strato(Aktuell)
#===========================================================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=unbekanten@gmail.com
#spring.mail.password=tvbnjoqslzdwfgmx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Mail Einstellungen für Strato SMTP
spring.mail.host=smtp.strato.de
spring.mail.port=465
spring.mail.username=code@hiobspost.de
spring.mail.password=Saturn18667
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

#==========================================================
# H2 + jar-erstellen
# jar erstellen in intelliJ terminal ohne Test für Strato Server (gibt kein Fehler aus)
# terminal@localhost HiobsServer % ./mvnw clean package -DskipTests
# Terminal: java -jar /Users/paulrichter/.m2/repository/com/h2database/h2/2.4.240/h2-2.4.240.jar
#==========================================================
# admin database H2 (in project integriert, für jar-datei nicht ändern)
spring.datasource.admin.jdbcUrl=jdbc:h2:file:./h2database/adminHiobs
spring.datasource.admin.driverClassName=org.h2.Driver
spring.datasource.admin.username=sa
spring.datasource.admin.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# hibernate, für die Tabellen erstellung
spring.jpa.hibernate.ddl-auto=update
#WARNUNG in console: die 'spring.jpa.open-in-view' is enabled by default.
spring.jpa.open-in-view = false

#==========================================================
# MongoDB Verbindung, Lokal für die Entwicklung ohne Name/Passwort
# ACHTUNG: spring boot ab ver. 4 ohne 'data' verbinden, einfach 'spring.mongodb.uri'
#==========================================================
spring.mongodb.uri=mongodb://localhost:27017/hiobspost

# für Jar Datei, auf Strato Server verbindung zu MongoDB herstellen, 100%
#spring.mongodb.uri=mongodb://hiobs:hiobsPost@localhost:27017/hiobspost?authSource=hiobspost

# Dieser einstellung für Strato Server(jar datei) funktioniere auch
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=hiobspost
#spring.mongodb.username=hiobs
#spring.mongodb.password=hiobsPost
#das hier ist der entscheidende Schlüssel, der oft vergessen wird:
#spring.mongodb.authentication-database=hiobspost


# :::::::::::::::::::::::::::::::::::::::::::::::
#   Pom.xml: Daten aus dem pom.xml abrufen und
#   Controller: @Value("${project.version}")
#               private String versions;
# :::::::::::::::::::::::::::::::::::::::::::::::
project.groupId=@pom.groupId@
project.artifactId=@pom.artifactId@
project.name=@pom.name@
project.version=@pom.version@
